on: push
name: ğŸš€ New Number System
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: aadarshasubedi/number-system@0.0.0
      with:
        server: ftp.lugakin.com
        username: numbersystem@lugakin.com
        password: o]KqFy;9n6M91Y
